Aws auth support
DelineaXPM/terraform-provider-dsv pull request #9
Opened 2022-08-08 01:12 UTC by 4killo

- make the client id and secret default

2022-08-08 18:10 UTC, sheldonhull requested changes

2022-08-09 13:30 UTC, 4killo commented on provider.go
> -				Sensitive:   true,
Good Catch! definitely this need to be sensitive

2022-08-09 13:33 UTC, 4killo commented on provider.go
> -				Sensitive:   true,
auth provider  should not be sensitive

2022-08-09 13:58 UTC, sheldonhull approved these changes

2022-08-09 13:58 UTC, merged